### ISSUE TITLE
今天下午貌似失效了？没获取到签到消息。

### ISSUE THREAD

**Issue by 13631181823** [aowubulao/auto-cpdaily#11]
今天下午貌似失效了？没获取到签到消息。
我请假回家会有影响吗？谢谢小哥！👏👏👏优秀

**Comment by 13631181823** [comment]
实际未签，求更新mua
执行日志

UTF-8
START RequestId:d0dffa83-900c-4373-9d3c-2e2879ed1990

13:37:21.751 [main] INFO daily.AutoDailyCp - 程序启动... By Neo

13:37:21.752 [main] INFO daily.AutoDailyCp - 程序初始化中...

13:37:22.160 [main] INFO daily.AutoDailyCp - 今日校园登陆成功

13:37:22.246 [main] INFO daily.AutoDailyCp - **当前时间段未获取到签到信息** 

END RequestId:d0dffa83-900c-4373-9d3c-2e2879ed1990

**Comment by aowubulao** [comment]
已经更新了，目前发现的问题是如果你已经请假离校，打卡会变成这样：

![](https://img.neoniou.com/blog/20210124123720.png)

这个脚本之前的逻辑没有去请求这个已请假（leaveTasks）的任务，所以会显示没有获取到

如果你是这个问题的话，那下载新版就可以解决
