### ISSUE TITLE
每天晨间签到都不行，晚间签到和晚检都可以，求大佬看一下

### ISSUE THREAD

**Issue by nickkking** [aowubulao/auto-cpdaily#13]
START RequestId: 67936de3-a648-4b9c-b510-e32e92fdaaaa

Event RequestId: 67936de3-a648-4b9c-b510-e32e92fdaaaa

02:23:22.146 [main] INFO daily.AutoDailyCp - 程序启动... By Neo

02:23:22.146 [main] INFO daily.AutoDailyCp - 程序初始化中...

02:23:22.812 [main] INFO daily.AutoDailyCp - 今日校园登陆成功

02:23:22.991 [main] INFO daily.AutoDailyCp - 当前时间段未获取到签到信息

END RequestId: 67936de3-a648-4b9c-b510-e32e92fdaaaa

Report RequestId: 67936de3-a648-4b9c-b510-e32e92fdaaaa Duration:847ms Memory:256MB MemUsage:130.375MB

**Comment by 13631181823** [comment]
大佬估计放假爽了😂

**Comment by aowubulao** [comment]
可以看一下是不是：https://github.com/aowubulao/auto-cpdaily/issues/11#issuecomment-766290328

这个情况出现的问题，如果是的话，下载1.3.1就可以解决
