### ISSUE TITLE
云函数调用失败

### ISSUE THREAD

**Issue by Jeekate** [aowubulao/auto-cpdaily#3]
2020-10-23下午15:30以后开始调用失败，查询日志如下
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
ERROR RequestId:ff43233b-5e8c-4629-94d7-db7c7b43e48e Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"java.lang.reflect.InvocationTargetException"}

**Comment by aowubulao** [comment]
问题是今日校园更换了新的API造成的，已经更新了。使用原来的链接下载新版就行。
