### ISSUE TITLE
显示今日校园版本过低，没有打卡成功！函数调用成功的。

### ISSUE THREAD

**Issue by 13631181823** [aowubulao/auto-cpdaily#6]
显示今日校园版本过低，没有打卡成功！函数调用成功的。
求更新！还有查寝！
mua！晚安💤！

**Comment by aowubulao** [comment]
显示旧版的没问题了。
查寝的需要解包最新的今日校园app，我目前没有合适的设备，所以可能会延后了。

**Comment by 13631181823** [comment]
> 显示旧版的没问题了。
> 查寝的需要解包最新的今日校园app，我目前没有合适的设备，所以可能会延后了。

感谢更新！❤️
