### ISSUE TITLE
签到信息错误，烦请老铁查看。

### ISSUE THREAD

**Issue by 13631181823** [aowubulao/auto-cpdaily#9]
日志:

START RequestId:080cc581-7889-4ffc-ba2f-1fc20e9a0903

11:05:05.383 [main] INFO daily.AutoDailyCp - 程序启动... By Neo

11:05:05.397 [main] INFO daily.AutoDailyCp - 程序初始化中...

11:05:07.494 [main] INFO daily.AutoDailyCp - 今日校园登陆成功

11:05:07.920 [main] INFO daily.AutoDailyCp - 获取到[1]条签到信息

**11:05:08.108 [main] INFO daily.request.SignRequest - 签到后的返回信息：[{"code":"2210010000","message":"请提交正确的签到信息","datas":null}]**

11:05:08.108 [main] INFO daily.AutoDailyCp - [73264]签到失败

11:05:08.108 [main] INFO daily.AutoDailyCp - 签到完成, 成功[0]条, 失败[1]条 

END RequestId:080cc581-7889-4ffc-ba2f-1fc20e9a0903

Report RequestId:080cc581-7889-4ffc-ba2f-1fc20e9a0903 Duration:3582ms Memory:256MB MemUsage:101.992188MB

**Comment by aowubulao** [comment]
已更新
